// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Nanoid from "nanoid";
import Zustand from "zustand";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function useNotes(param) {
  return Zustand((function (set, get) {
                return {
                        currentNoteIndex: 0,
                        notes: [{
                            title: "Hello, Note",
                            content: "You can basically enter anything here.",
                            id: Nanoid.nanoid()
                          }],
                        isEditing: true,
                        addNote: (function (title) {
                            return Curry._1(set, (function (state) {
                                          return {
                                                  currentNoteIndex: state.currentNoteIndex,
                                                  notes: Belt_Array.concat(state.notes, [{
                                                          title: title,
                                                          content: "",
                                                          id: Nanoid.nanoid()
                                                        }]),
                                                  isEditing: state.isEditing,
                                                  addNote: state.addNote,
                                                  deleteNote: state.deleteNote,
                                                  editNote: state.editNote,
                                                  setNoteIndex: state.setNoteIndex,
                                                  toggleMode: state.toggleMode,
                                                  saveToLocalStorage: state.saveToLocalStorage,
                                                  loadFromLocalStorage: state.loadFromLocalStorage
                                                };
                                        }));
                          }),
                        deleteNote: (function (id) {
                            return Curry._1(set, (function (state) {
                                          return {
                                                  currentNoteIndex: state.currentNoteIndex,
                                                  notes: Belt_Array.keep(state.notes, (function (note) {
                                                          return note.id !== id;
                                                        })),
                                                  isEditing: state.isEditing,
                                                  addNote: state.addNote,
                                                  deleteNote: state.deleteNote,
                                                  editNote: state.editNote,
                                                  setNoteIndex: state.setNoteIndex,
                                                  toggleMode: state.toggleMode,
                                                  saveToLocalStorage: state.saveToLocalStorage,
                                                  loadFromLocalStorage: state.loadFromLocalStorage
                                                };
                                        }));
                          }),
                        editNote: (function (note) {
                            return Curry._1(set, (function (state) {
                                          return {
                                                  currentNoteIndex: state.currentNoteIndex,
                                                  notes: Belt_Array.map(state.notes, (function (n) {
                                                          if (note.id === n.id) {
                                                            return n;
                                                          } else {
                                                            return note;
                                                          }
                                                        })),
                                                  isEditing: state.isEditing,
                                                  addNote: state.addNote,
                                                  deleteNote: state.deleteNote,
                                                  editNote: state.editNote,
                                                  setNoteIndex: state.setNoteIndex,
                                                  toggleMode: state.toggleMode,
                                                  saveToLocalStorage: state.saveToLocalStorage,
                                                  loadFromLocalStorage: state.loadFromLocalStorage
                                                };
                                        }));
                          }),
                        setNoteIndex: (function (index) {
                            return Curry._1(set, (function (state) {
                                          return {
                                                  currentNoteIndex: index,
                                                  notes: state.notes,
                                                  isEditing: state.isEditing,
                                                  addNote: state.addNote,
                                                  deleteNote: state.deleteNote,
                                                  editNote: state.editNote,
                                                  setNoteIndex: state.setNoteIndex,
                                                  toggleMode: state.toggleMode,
                                                  saveToLocalStorage: state.saveToLocalStorage,
                                                  loadFromLocalStorage: state.loadFromLocalStorage
                                                };
                                        }));
                          }),
                        toggleMode: (function (param) {
                            return Curry._1(set, (function (state) {
                                          return {
                                                  currentNoteIndex: state.currentNoteIndex,
                                                  notes: state.notes,
                                                  isEditing: !state.isEditing,
                                                  addNote: state.addNote,
                                                  deleteNote: state.deleteNote,
                                                  editNote: state.editNote,
                                                  setNoteIndex: state.setNoteIndex,
                                                  toggleMode: state.toggleMode,
                                                  saveToLocalStorage: state.saveToLocalStorage,
                                                  loadFromLocalStorage: state.loadFromLocalStorage
                                                };
                                        }));
                          }),
                        saveToLocalStorage: (function (param) {
                            var state = Curry._1(get, undefined);
                            var savedState_currentNoteIndex = state.currentNoteIndex;
                            var savedState_notes = state.notes;
                            var savedState_isEditing = state.isEditing;
                            var savedState_addNote = state.addNote;
                            var savedState_deleteNote = state.deleteNote;
                            var savedState_editNote = state.editNote;
                            var savedState_setNoteIndex = state.setNoteIndex;
                            var savedState_toggleMode = state.toggleMode;
                            var savedState_saveToLocalStorage = state.saveToLocalStorage;
                            var savedState_loadFromLocalStorage = state.loadFromLocalStorage;
                            var savedState = {
                              currentNoteIndex: savedState_currentNoteIndex,
                              notes: savedState_notes,
                              isEditing: savedState_isEditing,
                              addNote: savedState_addNote,
                              deleteNote: savedState_deleteNote,
                              editNote: savedState_editNote,
                              setNoteIndex: savedState_setNoteIndex,
                              toggleMode: savedState_toggleMode,
                              saveToLocalStorage: savedState_saveToLocalStorage,
                              loadFromLocalStorage: savedState_loadFromLocalStorage
                            };
                            var json = JSON.stringify(savedState);
                            if (json !== undefined) {
                              window.localStorage.setItem("state", json);
                            } else {
                              window.localStorage.setItem("state", "{}");
                            }
                            
                          }),
                        loadFromLocalStorage: (function (param) {
                            return Curry._1(set, (function (_state) {
                                          return JSON.parse(window.localStorage.getItem("state"));
                                        }));
                          })
                      };
              }), param);
}

export {
  useNotes ,
  
}
/* nanoid Not a pure module */
