// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import ReactMarkdown from "react-markdown";
import * as TheEditorComponent from "./TheEditorComponent";
import * as TheEditorModuleCss from "./TheEditor.module.css";

var styles = TheEditorModuleCss;

var components = TheEditorComponent.components;

var ReactMarkdown$1 = {};

function TheEditor(Props) {
  var onChangeContent = Props.onChangeContent;
  var onChangeTitle = Props.onChangeTitle;
  var onToggleMode = Props.onToggleMode;
  var isEditing = Props.isEditing;
  var currentNote = Props.currentNote;
  return React.createElement("div", {
              className: styles.theEditor
            }, React.createElement("div", {
                  className: styles.tabs
                }, React.createElement("button", {
                      className: styles.tab,
                      onClick: onToggleMode
                    }, "Edit Mode")), React.createElement("div", {
                  className: styles.editorContent + " " + (
                    isEditing ? styles.isEditing : ""
                  )
                }, isEditing ? React.createElement(React.Fragment, undefined, React.createElement("input", {
                            className: styles.titleInput,
                            placeholder: "Title here.",
                            type: "text",
                            value: currentNote.title,
                            onChange: onChangeTitle
                          }), React.createElement("textarea", {
                            className: styles.contentInput,
                            placeholder: "Content here",
                            value: currentNote.content,
                            onChange: onChangeContent
                          })) : React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, currentNote.title), React.createElement(ReactMarkdown, {
                            children: currentNote.content,
                            components: components
                          }))));
}

var make = TheEditor;

export {
  styles ,
  components ,
  ReactMarkdown$1 as ReactMarkdown,
  make ,
  
}
/* styles Not a pure module */
