// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TheEditor(Props) {
  return React.createElement("div", undefined, "HOho");
}

var make = TheEditor;

export {
  make ,
  
}
/* react Not a pure module */
