// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TheSidebar(Props) {
  return React.createElement("div", undefined, "Hohoko");
}

var make = TheSidebar;

export {
  make ,
  
}
/* react Not a pure module */
