// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", undefined, "Jojo");
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
