// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TheEditor from "./components/TheEditor.bs.js";
import * as TheSidebar from "./components/TheSidebar.bs.js";
import * as AppModuleCss from "./App.module.css";

var styles = AppModuleCss;

function App(Props) {
  return React.createElement("div", undefined, React.createElement(TheEditor.make, {}), React.createElement(TheSidebar.make, {}));
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
