// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as NoteStore from "./stores/NoteStore.bs.js";
import * as TheEditor from "./components/TheEditor.bs.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as TheSidebar from "./components/TheSidebar.bs.js";
import * as AppModuleCss from "./App.module.css";

var styles = AppModuleCss;

function App(Props) {
  var boxed = NoteStore.useNotes(function (state) {
        return {
                TAG: /* UnitFunc */4,
                _0: state.loadFromLocalStorage
              };
      });
  React.useEffect((function () {
          if (boxed.TAG === /* UnitFunc */4) {
            Curry._1(boxed._0, undefined);
          } else {
            Pervasives.failwith("Something wrong");
          }
          
        }), []);
  return React.createElement("div", undefined, React.createElement(TheEditor.make, {}), React.createElement(TheSidebar.make, {}));
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
